# Generated by Django 5.2.9 on 2025-12-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestorProductos', '0002_antiparasitario_remove_medicamento_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('url_imagen', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (0 = primera)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
