# Generated by Django 5.0.1 on 2025-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0006_alter_citamedica_tipo_mascota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='mascota',
            field=models.CharField(max_length=100, verbose_name='Nombre de Mascota'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='tipo_mascota',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('hamster', 'Hamster'), ('otro', 'Otro')], default='otro', max_length=10, verbose_name='Tipo de Mascota'),
        ),
    ]
