# Generated by Django 5.2.9 on 2025-12-06 00:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0007_alter_citamedica_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarioprofile',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='especialidades',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Especialidades (separadas por comas)'),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_domingo',
            field=models.CharField(blank=True, default='Cerrado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_jueves',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_lunes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_martes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_miercoles',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_sabado',
            field=models.CharField(blank=True, default='09:00 - 13:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='horario_viernes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='registro_profesional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Profesional'),
        ),
        migrations.AddField(
            model_name='veterinarioprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta')),
                ('motivo', models.TextField(verbose_name='Motivo de Consulta')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Síntomas')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Consulta')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='gestorUser.citamedica', verbose_name='Cita Relacionada')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='EgresoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Egresada')),
                ('fecha_egreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Egreso')),
                ('motivo', models.TextField(verbose_name='Motivo del Egreso')),
                ('paciente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paciente')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_medicamentos', to='gestorUser.consulta', verbose_name='Consulta Relacionada')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario Responsable')),
            ],
            options={
                'verbose_name': 'Egreso de Medicamento',
                'verbose_name_plural': 'Egresos de Medicamentos',
                'ordering': ['-fecha_egreso'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('tipo_mascota', models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('hamster', 'Hamster'), ('otro', 'Otro')], max_length=10, verbose_name='Tipo de Mascota')),
                ('raza', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza')),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('historial_medico', models.TextField(blank=True, null=True, verbose_name='Historial Médico')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias Conocidas')),
                ('medicamentos_permanentes', models.TextField(blank=True, null=True, verbose_name='Medicamentos Permanentes')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_clinicas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_clinicas', to='gestorUser.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='gestorUser.mascota', verbose_name='Mascota'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones')),
                ('valida_hasta', models.DateField(blank=True, null=True, verbose_name='Válida Hasta')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestorUser.consulta', verbose_name='Consulta')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=200, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=200, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=200, verbose_name='Duración')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='gestorUser.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tratamiento', models.CharField(max_length=200, verbose_name='Nombre del Tratamiento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Tratamiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='gestorUser.consulta', verbose_name='Consulta Relacionada')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='gestorUser.mascota', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=200, verbose_name='Nombre de la Vacuna')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de Aplicación')),
                ('fecha_proxima', models.DateField(blank=True, null=True, verbose_name='Próxima Aplicación')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Lote')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='gestorUser.mascota', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
