# Generated by Django 5.2.9 on 2025-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0008_veterinarioprofile_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, help_text='Ej: 2 años, 6 meses, etc.', max_length=50, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección del consultorio', null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='es_veterinario',
            field=models.BooleanField(default=False, help_text='Marque si este usuario es veterinario', verbose_name='Es Veterinario'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Especialidades médicas, separadas por comas', max_length=500, null=True, verbose_name='Especialidades (separadas por comas)'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_domingo',
            field=models.CharField(blank=True, default='Cerrado', max_length=100, null=True, verbose_name='Horario Domingo'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_jueves',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='Horario Jueves'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_lunes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='Horario Lunes'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_martes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='Horario Martes'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_miercoles',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='Horario Miércoles'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_sabado',
            field=models.CharField(blank=True, default='09:00 - 13:00', max_length=100, null=True, verbose_name='Horario Sábado'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='horario_viernes',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='Horario Viernes'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='registro_profesional',
            field=models.CharField(blank=True, help_text='Número de registro profesional', max_length=50, null=True, verbose_name='Registro Profesional'),
        ),
        migrations.AlterField(
            model_name='veterinarioprofile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
